from django.conf.urls import url, include
from rest_framework_mongoengine import routers

from . import views
from . import serializers

# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'restaurants', serializers.restaurantsViewSet, r"restaurants")

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.list, name='list'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add/$', views.add, name='add'),
    url(r'^restaurant/(?P<id>[0-9]+)$', views.restaurant, name='restaurant'),
    url(r'^images/(?P<id>[0-9]+)$', views.show_image, name='show_image'),
    url(r'^number/$', views.number_of_restaurants, name='number_of_restaurants'),
    # REST API root view (generated by DRF router)
    url(r'^api/', include(router.urls, namespace='api')),
]
